Repository VedantKhairnar/The-Meme-Repo, pull requests merged in 2020-10, with the labels that each got.

#11 New meme added to the c folder
  developerMemes/c-cpp/java and c meme.jpg
Labels: hacktoberfest

#10 Char meme!
  developerMemes/general/system32comic-char.jpg
Labels: hacktoberfest

#13 Additional memes
  Developper.png
  Error.png
  Privacy.png
  developerMemes/general/Developper.png
  developerMemes/general/Error.png
  developerMemes/general/Privacy.png
Labels: hacktoberfest

#14 meme
  developerMemes/general/among-us.jpeg
Labels: hacktoberfest

#15 Improved Structuring
  Developper.png
  Error.png
  Privacy.png
Labels: hacktoberfest

#16 Add Does-he-bite-html
  developerMemes/general/does-he-bite-html.png
Labels: hacktoberfest

#17 jobmemeadd
  developerMemes/Python Memes/pythonmeme.jpg
Labels: hacktoberfest-accepted

#18 prog looking prog
  developerMemes/general/prog meme.jpg
Labels: hacktoberfest, hacktoberfest-accepted

#20 Python Easy?
  developerMemes/Python Memes/pyEasy.jpg
Labels: hacktoberfest, hacktoberfest-accepted
